name: Terraform Deploy
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3 # Consider updating to @v4

    - name: Configure AWS Credentials # THIS STEP IS NEEDED
      uses: aws-actions/configure-aws-credentials@v4 # Use a recent version
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # If using temporary credentials
        aws-region: us-east-1 # Or your desired region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2 # Consider updating to @v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      # Consider: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      # Consider: terraform apply -auto-approve tfplan (if using -out with plan)
